#include "db/object_info_load.hpp"

#include "db/ddl.hpp"
#include "db/catalog_mssql.hpp"
#include "db/mssql_object.hpp"
#include "db/mysql_object.hpp"
#include "db/catalog_sqlanywhere.hpp"
#include "db/drivers/sqlanywhere.hpp"
#include "db/sqlanywhere_object.hpp"

namespace otter::db {
namespace {

void note(ObjectInfo& info, std::string_view part, const Error& error) {
    if (!info.error.empty()) info.error += "\n";
    info.error += std::string(part) + ": " + error.to_string();
}

// Uma linha de pares rotulo/valor: o nome de cada coluna e' o rotulo.
std::vector<ObjectProperty> row_as_properties(const ResultSet& rs, ObjectType type) {
    std::vector<ObjectProperty> out;
    if (rs.row_count() == 0) return out;

    out.reserve(rs.column_count());
    for (std::size_t c = 0; c < rs.column_count(); ++c) {
        ObjectProperty property;
        property.name  = std::string(rs.column(c).info().name);
        property.value = rs.is_null(0, c) ? std::string{} : std::string(rs.text(0, c));
        property.edit  = editable_property(type, property.name);
        out.push_back(std::move(property));
    }
    return out;
}

std::string property_value(const std::vector<ObjectProperty>& properties,
                           std::string_view name) {
    for (const ObjectProperty& property : properties) {
        if (property.name == name) return property.value;
    }
    return {};
}

} // namespace

Result<std::string> load_pg_table_ddl(PostgresCatalog& catalog, Holt& holt,
                                      const ObjectRef& ref,
                                      std::string_view partition_by,
                                      std::string_view comment) {
    TableMeta table;
    table.name    = ref.name;
    table.kind    = ref.type == ObjectType::foreign_table ? ObjKind::foreign_table
                                                          : ObjKind::table;
    table.comment = std::string(comment);

    OTTER_ASSIGN_OR_RETURN(table.columns, catalog.load_columns(ref.schema, ref.name));
    table.columns_loaded = true;
    OTTER_ASSIGN_OR_RETURN(table.constraints,
                           catalog.load_constraints(ref.schema, ref.name));
    table.constraints_loaded = true;
    OTTER_ASSIGN_OR_RETURN(table.indexes, catalog.load_indexes(ref.schema, ref.name));
    table.indexes_loaded = true;
    OTTER_ASSIGN_OR_RETURN(table.foreign_keys,
                           catalog.load_table_foreign_keys(ref.schema, ref.name));

    // Serial, identity e coluna gerada. O catalogo de colunas as entrega como
    // "integer DEFAULT nextval('t_id_seq')" -- e um CREATE TABLE escrito assim
    // falha, porque a sequencia so' existe DEPOIS da tabela (e' ela que a
    // cria). A coluna gerada sairia como DEFAULT, que e' outra coisa: aceita
    // valor no INSERT.
    {
        const ServerVersion version = catalog.version();
        const std::string sql =
            "SELECT a.attname,"
            "       " + std::string(version.at_least(10) ? "a.attidentity::text" : "''") + ","
            "       " + std::string(version.at_least(12) ? "a.attgenerated::text" : "''") + ","
            "       COALESCE(pg_get_serial_sequence(" +
            // O PRIMEIRO argumento e' texto que o servidor interpreta como
            // nome: precisa das aspas duplas, dentro do literal.
            pg_regclass(ref.schema, ref.name) + "::text, a.attname), '')"
            "  FROM pg_attribute a"
            " WHERE a.attrelid = " + pg_regclass(ref.schema, ref.name) +
            "   AND a.attnum > 0 AND NOT a.attisdropped";
        OTTER_ASSIGN_OR_RETURN(auto rs, holt.query(sql));

        for (std::size_t r = 0; r < rs.row_count(); ++r) {
            const std::string_view name      = rs.text(r, 0);
            const std::string_view identity  = rs.text(r, 1);
            const std::string_view generated = rs.text(r, 2);
            const std::string_view sequence  = rs.text(r, 3);

            for (ColumnMeta& column : table.columns) {
                if (column.name != name) continue;

                if (identity == "a" || identity == "d") {
                    column.type_name += identity == "a"
                                            ? " GENERATED ALWAYS AS IDENTITY"
                                            : " GENERATED BY DEFAULT AS IDENTITY";
                    column.default_value.clear();
                } else if (generated == "s") {
                    column.type_name += " GENERATED ALWAYS AS (" +
                                        column.default_value + ") STORED";
                    column.default_value.clear();
                } else if (!sequence.empty() &&
                           column.default_value.starts_with("nextval(")) {
                    if (column.type_name == "integer")       column.type_name = "serial";
                    else if (column.type_name == "bigint")   column.type_name = "bigserial";
                    else if (column.type_name == "smallint") column.type_name = "smallserial";
                    else break;   // tipo inesperado: fica o DEFAULT, a' vista
                    column.default_value.clear();
                }
                break;
            }
        }
    }

    // O indice de uma constraint UNIQUE nasce com ela, como o da PK: repeti-lo
    // como CREATE INDEX daria "relacao ja' existe" ao rodar o script.
    std::erase_if(table.indexes, [&table](const IndexMeta& index) {
        for (const ConstraintMeta& constraint : table.constraints) {
            if (constraint.name == index.name) return true;
        }
        return false;
    });

    std::string ddl = generate_ddl(ref.schema, table);

    if (ref.type == ObjectType::foreign_table) {
        // generate_ddl escreve CREATE TABLE; a clausula SERVER nao esta' no
        // modelo. O comando sai marcado, em vez de parecer completo.
        const std::string head = "CREATE TABLE ";
        if (ddl.starts_with(head)) ddl.replace(0, head.size(), "CREATE FOREIGN TABLE ");
        ddl += "\n-- SERVER and OPTIONS are not shown: see the foreign server\n";
    }

    if (!partition_by.empty()) {
        // O fecho do CREATE TABLE e' o primeiro ");\n" em inicio de linha.
        const std::size_t close = ddl.find("\n);\n");
        if (close != std::string::npos) {
            ddl.replace(close, 4, "\n) PARTITION BY " + std::string(partition_by) + ";\n");
        }
    }

    // As chaves estrangeiras DEPOIS da tabela, como ALTER: a tabela
    // referenciada pode vir depois num script com varias.
    const std::string full = qualified_name(ref.schema, ref.name);
    bool first = true;
    for (const ForeignKeyMeta& key : table.foreign_keys) {
        if (key.definition.empty()) continue;
        if (first) { ddl += "\n"; first = false; }
        ddl += "ALTER TABLE " + full + " ADD CONSTRAINT " + quote_if_needed(key.name) +
               " " + key.definition + ";\n";
    }
    return ddl;
}

ObjectInfo load_object_info(PostgresCatalog& catalog, Holt& holt, const ObjectRef& ref) {
    ObjectInfo info;

    // O dialeto de citacao (db/ddl.hpp) NAO e' trocado aqui: isto roda no
    // worker, e o estado e' lido pelo thread de UI. Quem abre o editor de um
    // objeto esta' com a conexao dele ativa, e o dialeto ja' e' o certo.
    if (auto rs = holt.query(pg_properties_query(ref))) {
        info.properties = row_as_properties(*rs, ref.type);
        if (info.properties.empty()) {
            // Zero linhas: o objeto foi removido ou renomeado por fora.
            info.error = "the object no longer exists; refresh the tree";
            return info;
        }
    } else {
        note(info, "properties", rs.error());
        return info;
    }

    if (const std::string sql = pg_statistics_query(ref); !sql.empty()) {
        if (auto rs = holt.query(sql)) {
            info.statistics = row_as_properties(*rs, ref.type);
            for (ObjectProperty& statistic : info.statistics) {
                statistic.edit = ObjectEdit::none;
            }
        } else {
            note(info, "statistics", rs.error());
        }
    }

    if (ref.type == ObjectType::table || ref.type == ObjectType::foreign_table) {
        auto ddl = load_pg_table_ddl(catalog, holt, ref,
                                     property_value(info.properties, "Partition by"),
                                     property_value(info.properties, "Comment"));
        if (ddl) info.ddl = std::move(*ddl);
        else     note(info, "DDL", ddl.error());
    } else if (const std::string sql = pg_ddl_query(ref); !sql.empty()) {
        if (auto rs = holt.query(sql)) {
            for (std::size_t r = 0; r < rs->row_count(); ++r) {
                if (rs->is_null(r, 0)) continue;
                if (!info.ddl.empty()) info.ddl += "\n";
                info.ddl += std::string(rs->text(r, 0));
            }
            if (!info.ddl.empty() && info.ddl.back() != '\n') info.ddl.push_back('\n');
        } else {
            note(info, "DDL", rs.error());
        }
    }

    if (const std::string sql = pg_permissions_query(ref); !sql.empty()) {
        info.has_permissions = true;
        if (auto rs = holt.query(sql)) {
            info.permissions.reserve(rs->row_count());
            for (std::size_t r = 0; r < rs->row_count(); ++r) {
                ObjectPermission permission;
                permission.grantee   = std::string(rs->text(r, 0));
                permission.privilege = std::string(rs->text(r, 1));
                const std::string_view grantable = rs->text(r, 2);
                permission.grantable = grantable == "t" || grantable == "true";
                permission.grantor   = std::string(rs->text(r, 3));
                info.permissions.push_back(std::move(permission));
            }
        } else {
            note(info, "permissions", rs.error());
        }
    }
    return info;
}

ObjectInfo load_object_info(MysqlCatalog&, Holt& holt, const ObjectRef& ref) {
    ObjectInfo info;

    const std::string properties = mysql_properties_query(ref);
    if (properties.empty()) {
        info.error = "the object editor does not cover this object type on MySQL";
        return info;
    }

    if (auto rs = holt.query(properties)) {
        info.properties = row_as_properties(*rs, ref.type);
        // O que se altera no MySQL e' outro conjunto (db/mysql_object.cpp):
        // RENAME TABLE, COMMENT de tabela/rotina/evento. Chamado direto, e
        // nao pelo dialeto global -- isto roda no worker.
        for (ObjectProperty& property : info.properties) {
            property.edit = mysql_editable_property(ref.type, property.name);
        }
        if (info.properties.empty()) {
            info.error = "the object no longer exists; refresh the tree";
            return info;
        }
    } else {
        note(info, "properties", rs.error());
        return info;
    }

    if (const MysqlShowCreate show = mysql_show_create(ref); !show.sql.empty()) {
        if (auto rs = holt.query(show.sql)) {
            if (rs->row_count() > 0 && show.column < rs->column_count() &&
                !rs->is_null(0, show.column)) {
                info.ddl = std::string(rs->text(0, show.column)) + ";\n";
            }
        } else {
            note(info, "DDL", rs.error());
        }
    }

    if (const std::string sql = mysql_permissions_query(ref); !sql.empty()) {
        info.has_permissions = true;
        if (auto rs = holt.query(sql)) {
            info.permissions.reserve(rs->row_count());
            for (std::size_t r = 0; r < rs->row_count(); ++r) {
                ObjectPermission permission;
                permission.grantee   = std::string(rs->text(r, 0));
                permission.privilege = std::string(rs->text(r, 1));
                permission.grantable = rs->text(r, 2) == "1";
                permission.grantor   = std::string(rs->text(r, 3));
                info.permissions.push_back(std::move(permission));
            }
        } else {
            note(info, "permissions", rs.error());
        }
    }
    return info;
}

// --- SQL Server ------------------------------------------------------------------------

ObjectInfo load_object_info(MssqlCatalog& catalog, Holt& holt, const ObjectRef& ref) {
    ObjectInfo info;

    const std::string properties = mssql_properties_query(ref);
    if (properties.empty()) {
        info.error = "the object editor does not cover this object type on SQL Server";
        return info;
    }

    if (auto rs = holt.query_internal(properties)) {
        info.properties = row_as_properties(*rs, ref.type);
        // Chamado direto, e nao pelo dialeto do thread: nao depende de quem
        // chamou ter posto o dialeto certo.
        for (ObjectProperty& property : info.properties) {
            property.edit = mssql_editable_property(ref.type, property.name);
        }
        if (info.properties.empty()) {
            info.error = "the object no longer exists; refresh the tree";
            return info;
        }
    } else {
        note(info, "properties", rs.error());
        return info;
    }

    if (ref.type == ObjectType::table) {
        // O SQL Server nao tem um "SHOW CREATE TABLE": o comando e' montado
        // das colunas, constraints, indices e chaves que o catalogo le'.
        TableMeta table;
        table.name    = ref.name;
        table.kind    = ObjKind::table;
        table.comment = property_value(info.properties, "Comment");

        auto columns = catalog.load_columns(ref.schema, ref.name);
        if (!columns) {
            note(info, "DDL", columns.error());
        } else {
            table.columns = std::move(*columns);
            if (auto constraints = catalog.load_constraints(ref.schema, ref.name)) {
                table.constraints = std::move(*constraints);
            }
            if (auto indexes = catalog.load_indexes(ref.schema, ref.name)) {
                table.indexes = std::move(*indexes);
            }
            if (auto keys = catalog.load_table_foreign_keys(ref.schema, ref.name)) {
                table.foreign_keys = std::move(*keys);
            }

            // Semente e incremento das colunas identity.
            std::vector<MssqlIdentity> identity;
            if (auto rs = holt.query_internal(
                    "SELECT ic.name, CAST(ic.seed_value AS bigint),"
                    "       CAST(ic.increment_value AS bigint)"
                    "  FROM sys.identity_columns ic"
                    " WHERE ic.object_id = " + mssql_object_id(ref.schema, ref.name))) {
                for (std::size_t r = 0; r < rs->row_count(); ++r) {
                    identity.push_back({std::string(rs->text(r, 0)),
                                        "IDENTITY(" + std::string(rs->text(r, 1)) + "," +
                                            std::string(rs->text(r, 2)) + ")"});
                }
            }
            info.ddl = mssql_table_ddl(ref.schema, table, identity);
        }
    } else if (const std::string sql = mssql_definition_query(ref); !sql.empty()) {
        if (auto rs = holt.query_internal(sql)) {
            if (rs->row_count() > 0 && !rs->is_null(0, 0)) {
                info.ddl = std::string(rs->text(0, 0));
                if (!info.ddl.empty() && info.ddl.back() != '\n') info.ddl.push_back('\n');
            } else {
                // NULL: WITH ENCRYPTION, CLR, ou falta VIEW DEFINITION.
                note(info, "DDL",
                     Error{Errc::not_found,
                           "the definition is not available (encrypted, CLR, or no "
                           "VIEW DEFINITION permission)"});
            }
        } else {
            note(info, "DDL", rs.error());
        }
    }

    if (const std::string sql = mssql_permissions_query(ref); !sql.empty()) {
        info.has_permissions = true;
        if (auto rs = holt.query_internal(sql)) {
            info.permissions.reserve(rs->row_count());
            for (std::size_t r = 0; r < rs->row_count(); ++r) {
                ObjectPermission permission;
                permission.grantee   = rs->is_null(r, 0) ? std::string{}
                                                         : std::string(rs->text(r, 0));
                permission.privilege = std::string(rs->text(r, 1));
                permission.grantable = rs->text(r, 2) == "1";
                permission.grantor   = rs->is_null(r, 3) ? std::string{}
                                                         : std::string(rs->text(r, 3));
                info.permissions.push_back(std::move(permission));
            }
        } else {
            note(info, "permissions", rs.error());
        }
    }
    return info;
}

// --- SQL Anywhere -----------------------------------------------------------------------

ObjectInfo load_object_info(SqlAnywhereCatalog& catalog, Holt& holt,
                            const ObjectRef& ref) {
    ObjectInfo info;

    const std::string properties = sqlanywhere_properties_query(ref);
    if (properties.empty()) {
        info.error = "the object editor does not cover this object type on SQL Anywhere";
        return info;
    }

    if (auto rs = holt.query_internal(properties)) {
        info.properties = row_as_properties(*rs, ref.type);
        // Chamado direto, e nao pelo dialeto do thread: nao depende de quem
        // chamou ter posto o dialeto certo.
        for (ObjectProperty& property : info.properties) {
            property.edit = sqlanywhere_editable_property(ref.type, property.name);

            // "2014-11-24 17:08:28.000000": a consulta do programa nao passa
            // pelo ajuste que a grade faz, e a fracao inteira saia na tela
            // (visto na captura). So' no que tem a forma de data e hora.
            const std::string& value = property.value;
            if (value.size() >= 19 && value[4] == '-' && value[7] == '-' &&
                value[10] == ' ' && value[13] == ':' && value[16] == ':') {
                property.value = sqlanywhere_trim_fraction(value);
            }
        }
        if (info.properties.empty()) {
            info.error = "the object no longer exists; refresh the tree";
            return info;
        }
    } else {
        note(info, "properties", rs.error());
        return info;
    }

    // O servidor escreve com CRLF; o editor trabalha com LF.
    const auto set_ddl = [&info](std::string_view text) {
        info.ddl.clear();
        info.ddl.reserve(text.size());
        for (const char c : text) {
            if (c != '\r') info.ddl.push_back(c);
        }
        if (!info.ddl.empty() && info.ddl.back() != '\n') info.ddl.push_back('\n');
    };

    if (ref.type == ObjectType::table) {
        // Caminho proprio: a funcao do servidor troca opcoes da conexao, e o
        // catalogo as repoe.
        if (auto ddl = catalog.load_table_definition(ref.schema, ref.name)) {
            set_ddl(*ddl);
        } else {
            note(info, "DDL", ddl.error());
        }
    } else if (ref.type == ObjectType::event) {
        if (auto ddl = catalog.load_event_definition(ref.name)) {
            set_ddl(*ddl);
        } else {
            note(info, "DDL", ddl.error());
        }
    } else if (const std::string sql = sqlanywhere_definition_query(ref); !sql.empty()) {
        if (auto rs = holt.query_internal(sql)) {
            if (rs->row_count() > 0 && !rs->is_null(0, 0)) {
                set_ddl(rs->text(0, 0));
            } else {
                note(info, "DDL",
                     Error{Errc::not_found,
                           "the definition is not available (hidden, or no permission)"});
            }
        } else {
            note(info, "DDL", rs.error());
        }
    }

    if (const std::string sql = sqlanywhere_permissions_query(ref); !sql.empty()) {
        info.has_permissions = true;
        if (auto rs = holt.query_internal(sql)) {
            info.permissions.reserve(rs->row_count());
            for (std::size_t r = 0; r < rs->row_count(); ++r) {
                ObjectPermission permission;
                permission.grantee   = rs->is_null(r, 0) ? std::string{}
                                                         : std::string(rs->text(r, 0));
                permission.privilege = std::string(rs->text(r, 1));
                permission.grantable = rs->text(r, 2) == "1";
                permission.grantor   = rs->is_null(r, 3) ? std::string{}
                                                         : std::string(rs->text(r, 3));
                info.permissions.push_back(std::move(permission));
            }
        } else {
            note(info, "permissions", rs.error());
        }
    }
    return info;
}

} // namespace otter::db
